---
- name: Create Ubuntu 24.04 container on Proxmox
  hosts: localhost
  gather_facts: true
  vars:
    proxmox_host: "192.168.1.210"  # Ersetze dies mit deinem Proxmox-Hostname oder IP
    proxmox_user: "root@pam"  # API Benutzername
    proxmox_password: "your_password"  # API Passwort
    proxmox_node: "pve"  # Name des Proxmox Nodes, auf dem der Container erstellt werden soll
    storage: "local"  # Speicherort für den Container
    os_template: "local:vztmpl/ubuntu-24.04-standard_amd64.tar.gz"  # Ubuntu 24.04 Template
    password_length: 12  # Länge des zufälligen Passworts
  tasks:
    - name: Generate a random container ID that doesn't exist
      set_fact:
        container_id: "{{ lookup('pipe', 'pvesh get /nodes/' + proxmox_node + '/lxc | jq -r \'.[].vmid\'') | map('int') | max + 1 }}"

    - name: Generate a random container name
      set_fact:
        container_name: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"

    - name: Generate a random root password
      set_fact:
        root_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters') }}"

    - name: Create LXC container on Proxmox
      community.proxmox.proxmox_lxc:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ container_id }}"
        hostname: "{{ container_name }}"
        password: "{{ root_password }}"
        cores: 2
        memory: 2048
        swap: 2048
        netif:
          - name: eth0
            bridge: vmbr0
            ip: dhcp
        storage: "{{ storage }}"
        ostemplate: "{{ os_template }}"
        force: true
        state: started

    - name: Show container details
      debug:
        msg:
          - "Container ID: {{ container_id }}"
          - "Container Name: {{ container_name }}"
          - "Container Password: {{ root_password }}"
